// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyNetworkSetup():Promise<string>;

export function GetPlatform():Promise<string>;

export function Log():Promise<string>;

export function StartTunnel(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function Status():Promise<main.Status>;

export function StopTunnel():Promise<void>;

export function UndoNetworkSetup():Promise<string>;
