// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyNetworkSetup() {
  return window['go']['main']['App']['ApplyNetworkSetup']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function Log() {
  return window['go']['main']['App']['Log']();
}

export function StartTunnel(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartTunnel'](arg1, arg2, arg3, arg4);
}

export function Status() {
  return window['go']['main']['App']['Status']();
}

export function StopTunnel() {
  return window['go']['main']['App']['StopTunnel']();
}

export function UndoNetworkSetup() {
  return window['go']['main']['App']['UndoNetworkSetup']();
}
